import Navbar from "@/components/navbar/navbar";
import "./globals.css";

export const metadata = {
  title: "Coffee and Chill",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
